develop to main pull request
chemplexity/gcms-pipeline pull request #1
Opened 2024-07-12 18:42 UTC by iszabo0150

2024-07-20 00:08 UTC, chemplexity requested changes

2024-07-20 00:08 UTC, chemplexity commented on src/database/tables/samples_table_sql.txt
> +    time            REAL,
lets remove the following items from the samples table: time, intensity, channel, and baseline

2024-07-20 00:08 UTC, chemplexity commented on src/file/ExportNIST.m
> +function data = ExportNIST(sampleRow, channelArray, intensityArray, timeArray)
yes, lets have data as input so we can fill in the file_path, file_name, file_size

2024-07-20 00:08 UTC, chemplexity commented on scripts/addChecksum.m
> +for i=1: size(data, 1)
remove extra space before 'size'

2024-07-20 00:08 UTC, chemplexity commented on scripts/getAverageSpectraOfTimeRange.m
> +[startInd, endInd] = lookupTimeRangeIndex(timeArray, timeStart, timeEnd);
need to handle case where timeStart > all values in timeArray by throwing error message

2024-07-20 00:08 UTC, chemplexity commented on scripts/preprocessData.m
> +for i=1: size(data, 1)
remove extra space before 'size'

2024-07-20 00:08 UTC, chemplexity commented on src/database/CreateDatabase.m
> +
lets add a display message saying DB is created and show its path/filename.db

2024-07-20 00:08 UTC, chemplexity commented on src/database/tables/samples_table_sql.txt
> +    sequence_index  integer not null,
remove not null from sequence_index

2024-07-20 00:08 UTC, chemplexity commented on src/database/tables/peaks_table_sql.txt
> +    input_mode   TEXT,
remove input_mode

2024-07-20 00:08 UTC, chemplexity commented on tests/databaseUnitTest.m
> +conn = sqlite('/Users/isabella/Desktop/gcms-pipeline/src/database/GCMS_Database.db');
use relative path

2024-07-20 00:08 UTC, chemplexity commented on tests/unittestplaceholder.m
> +% Unit test placeholder
we can remove this file entirely, its ok to delete

2024-07-21 22:58 UTC, iszabo0150 commented on src/database/tables/samples_table_sql.txt
> +    time            REAL,
resolved

2024-07-22 18:01 UTC, merged